### ISSUE TITLE
defi.conf md5 hash

### ISSUE THREAD

**Issue by adrian-schnell** [defichain-api/masternode-health-server#19]
To recognize possible unwanted modifications on the `defi.conf` file, we should add the md5 hash of this file to the API calls.

what do you think about this @sandrich @DerFuchs ?

**Comment by sandrich** [comment]
Should be easy to implement. Do you think we should store the old hash locally as well or just send it to the api?

**Comment by adrian-schnell** [comment]
think we could do both..

1. storing it tmp on the server and only send a flag "conf_md5_changed" to the api
2. sending it all the time to the API - so the API server is responsible to detect the md5 hash change

at the moment I'm not sure what's better... maybe let's keep all the logic on the API server..?

**Comment by sandrich** [comment]
@adrian-schnell alerting is part of the api service I think so the logic should be there really.
