### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by GuybrushX** [defichain-api/masternode-health-server#28]
I get the following error:
$ pip install masterhode-health
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement masterhode-health (from versions: none)
ERROR: No matching distribution found for masterhode-health

pip and pip3 was tried.
$ pip -V
pip 21.2.4 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)

~$ pip3 -V
pip 21.2.4 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)

Any ideas?

**Comment by sandrich** [comment]
Hey, there is a typo in masternode-health :-)

'masterhode-health'

**Comment by GuybrushX** [comment]
@adrian-schnell will fix the README, there is the mistake - I thought it was my typo... ;-)

Did install successfully now. Thanks for the fast reply :-)
